### ISSUE TITLE
Fetching images through API

### ISSUE THREAD

**Issue by ganeshpatki** [GameOnCentennialCollege/GameOn#1]
Images path appears to be absolute path of the directory which is not convenient to pass through JSON to Android. 
Need to figure out the alternative way to pass image path through JSON.

**Comment by anchal-sharma** [comment]
Will you be able to fetch images if the image is in binary format?

**Comment by ganeshpatki** [comment]
I have to see if we can use the binary format. In products API send binary object instead of path.

**Comment by anchal-sharma** [comment]
Okay I will do that

**Comment by anchal-sharma** [comment]
Ganesh are you able to fetch images? Please try and let me know. Thanks

**Comment by anchal-sharma** [comment]
I have changed the path for all the images to full URL path.
