### ISSUE TITLE
Change Image from absolute path to binary path in database 

### ISSUE THREAD

**Issue by anchal-sharma** [GameOnCentennialCollege/GameOn#2]
As per the requirements please necessary changes to the database:
Change the image datatype from nvarchar to binary so that I can make APIs accordingly.

**Comment by salimmazumder69** [comment]
Okay I will fix that

**Comment by salimmazumder69** [comment]
I have changed the data type of the image from absolute path to base64. I have also added image in base64 format for one product, i.e, Wheel light, the very first product coming on the url http://gameon.enigmacondos.ca/api/products

**Comment by anchal-sharma** [comment]
I have changed the path for all the images to full URL path.
