### ISSUE TITLE
get sub-categories list

### ISSUE THREAD

**Issue by lakinpatel** [GameOnCentennialCollege/GameOn#5]
- on click of parent category, should return the sub-categories
  @anchal-sharma

**Comment by anchal-sharma** [comment]
Get all sub-categories 
http://www.gameon.enigmacondos.ca/api/subcategories/

Get sub-category details by its id
http://www.gameon.enigmacondos.ca/api/subcategories/subcategory?id=1

Get sub-categories list by category id
http://www.gameon.enigmacondos.ca/api/subcategories/category?id=1
