### ISSUE TITLE
user login

### ISSUE THREAD

**Issue by lakinpatel** [GameOnCentennialCollege/GameOn#8]
@anchal-sharma 
- there should be API for login, which accepts the username and password from user, and allows them to login into application

**Comment by anchal-sharma** [comment]
User Login in done. Here is the link to that: http://gameon.enigmacondos.ca/api/userdetails/login
You have to call this Web API using Post method.

**Comment by anchal-sharma** [comment]
username: anchal
password: wordpass

username: konika
password: wordpass
