### ISSUE TITLE
user registration

### ISSUE THREAD

**Issue by lakinpatel** [GameOnCentennialCollege/GameOn#9]
@anchal-sharma 
- API to allow user to register him/her-self for the app,

**Comment by anchal-sharma** [comment]
Here is the link for user registration: http://gameon.enigmacondos.ca/api/userdetails/register
call this by post method
example (these are the fields you need to provide) 
userid: john
userpassword: wordpass
username: John Smith
useremail: john@gmail.com
userphone: 423123123
